version: '3'

services:
  java:
    build: ./java
    ports:
      - 8080:8080
    tty: true
    volumes:
      - ../src:/usr/src
  db:
    build: .
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      TZ: Asia/Tokyo
    volumes:
      - ./data:/var/lib/postgresql/data
      - ../src:/usr/src
    ports:
      - 5432:5432
